site_name: HandyLLM
site_url: https://atomiechen.github.io/handyllm
repo_url: https://github.com/atomiechen/HandyLLM
repo_name: atomiechen/HandyLLM
copyright: Copyright &copy; 2024 Atomie CHEN

watch:
  - docs_src
  - docs_overrides

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/atomiechen/HandyLLM
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/HandyLLM/
    - icon: material/microsoft-visual-studio-code
      link: https://marketplace.visualstudio.com/items?itemName=atomiechen.handyllm

theme:
  name: material
  custom_dir: docs_overrides
  logo: assets/icon_round.svg
  favicon: assets/icon_round.svg
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: custom
      accent: custom
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: custom
      accent: custom
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.tabs
    # - navigation.tabs.sticky
    - content.code.copy
    - announce.dismiss
    - navigation.top

markdown_extensions:
  - toc:
      permalink: true
  - mdx_include:
      base_path: docs
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.blocks.details
  - attr_list
  - md_in_html

extra_css:
  - stylesheets/theme.css
  - stylesheets/code.css
  - stylesheets/extra.css

plugins:
  - search
  - i18n:
      docs_structure: folder
      fallback_to_default: false
      languages:
        - locale: en
          default: true
          name: en - English
          build: true
          extra:
            announcement: <b>Support us!</b><a href="https://github.com/atomiechen/HandyLLM"> ğŸŒŸ Star HandyLLM</a> to help it spread and improve!
        - locale: zh
          name: zh - ç®€ä½“ä¸­æ–‡
          build: true
          nav_translations:
            Getting Started: å¿«é€Ÿä¸Šæ‰‹
          extra:
            announcement: <b>æ”¯æŒæˆ‘ä»¬ï¼</b><a href="https://github.com/atomiechen/HandyLLM">ç»™HandyLLMå°æ˜Ÿæ˜ŸğŸŒŸ</a> æ¥å¸®å®ƒä¼ æ’­æ”¹è¿›ï¼

nav:
  - HandyLLM: index.md
  - Getting Started: getting-started.md
